version: '3.8'
services:
  todos:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - USERS_SERVICE_URL=${USERS_SERVICE_URL}
    volumes:
      - .:/app
    depends_on:
      - db
      - users  # Add dependency on users service
    env_file:
      - .env

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  users:
    build:
      context: ../chalkboard_demo_users  # Path to users service Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ../chalkboard_demo_users:/app
    depends_on:
      - db
    env_file:
      - ../chalkboard_demo_users/.env

volumes:
  postgres_data:
