version: '3.8'
services:
  todos:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:BroytPGDB123!!@db:5432/ChalkboardDemo"
      USERS_SERVICE_URL: "http://users:8001"  # Set the URL for users service in Docker
    volumes:
      - .:/app
    depends_on:
      - db
      - users  # Add dependency on users service

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BroytPGDB123!!
      POSTGRES_DB: ChalkboardDemo
    volumes:
      - postgres_data:/var/lib/postgresql/data

  users:
    build:
      context: ../chalkboard_demo_users  # Path to users service Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:BroytPGDB123!!@db:5432/ChalkboardDemo"
    volumes:
      - ../chalkboard_demo_users:/app
    depends_on:
      - db

volumes:
  postgres_data:
